language: node_js
node_js:
- "9"
cache:
  directories:
  - node_modules
before_cache:
- rm -rf node_modules/.yarn-integrity
install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
script:
- yarn ci
before_deploy:
  # todo
deploy:
  # todo
